particle_filter:
  ros__parameters:
    
    update_rate: 50

    odom_topic: /odom
    steering_angle_topic: /steering_angle
    scan_topic: /scan
    pose_topic: /pose
    base_frame: base_link
    publish_tf: true
    publish_particles: true

    num_particles: 1000
    lidar_range_min: 0.0 
    lidar_range_max: 20.0 

    # Raycasting
    raycasting_method: 'GLT'
    theta_discretization: 112

    # RangeLib variant to use for range calculations. Allowed values:
    # 0: VAR_NO_EVAL_SENSOR_MODEL - No sensor model evaluation
    # 1: VAR_CALC_RANGE_MANY_EVAL_SENSOR - Calculate range with multiple evaluations
    # 2: VAR_REPEAT_ANGLES_EVAL_SENSOR - Repeat angles with sensor model evaluation
    # 3: VAR_REPEAT_ANGLES_EVAL_SENSOR_ONE_SHOT - One-shot evaluation with repeated angles
    # 4: VAR_RADIAL_CDDT_OPTIMIZATIONS - Radial optimizations for CDDT
    # Try variants: (rmgpu,2), (pcddt,3),(glt,3)
    rangelib_variant: 3
    
    # beam based sensor model
    z_hit: 0.85
    z_short: 0.10
    z_max: 0.025
    z_rand: 0.025
    sigma_hit: 0.1
    lambda_short: 0.25

    # inital pose
    use_initial_pose: true 
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_a: 0.0
    initial_cov_xx: 0.5
    initial_cov_yy: 0.5
    initial_cov_aa: 0.1
    
    # Lidar downsampling
    downsampling_method: 'BOX'
    box: 
      box_aspect_ratio: 3.5
      num_beams: 50
    uni:
      num_beams: 60



    # Motion model 
    motion_model: 'TUM'
    

    
